name: SmartKassa CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # ЗАДАЧА 1: Проверка стиля кода (Lint)
  lint:
    name: Проверка стиля кода
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка кода
        uses: actions/checkout@v4

      - name: Установка Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Права на gradlew
        run: chmod +x gradlew

      - name: Запуск Lint
        run: ./gradlew lintDebug

      - name: Сохранение отчёта Lint
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  # ЗАДАЧА 2: Unit-тесты
  unit-test:
    name: Unit-тесты
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Загрузка кода
        uses: actions/checkout@v4

      - name: Установка Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Права на gradlew
        run: chmod +x gradlew

      - name: Запуск Unit-тестов
        run: ./gradlew testDebugUnitTest

      - name: Сохранение отчёта тестов
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  # ЗАДАЧА 3: Сборка APK (без UI-тестов)
  build:
    name: Сборка APK
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Загрузка кода
        uses: actions/checkout@v4

      - name: Установка Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Права на gradlew
        run: chmod +x gradlew

      - name: Сборка APK
        run: ./gradlew assembleDebug

      - name: Сохранение APK
        uses: actions/upload-artifact@v4
        with:
          name: smartkassa-debug-apk
          path: app/build/outputs/apk/debug/*.apk